version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/worker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/clients/desktop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/clients/react"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/clients/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
